Simplifies introduction
vcstuff/draft-ietf-oauth-attestation-based-client-auth pull request #19
Opened 2023-06-13 19:52 UTC by tplooker

Re-simplifies the introduction

2023-06-27 20:21 UTC, selfissued approved these changes
I agree with this direction.  I would try to eliminate places where the spec appears to be make normative statements about having a backend.  (It's fine to say things like "1. A Client Attestation JWT - typically produced by the client backend.")

2023-06-27 20:45 UTC, c2bo approved these changes

2023-10-08 18:43 UTC, peppelinux requested changes
informally approved, formally requested two small editorial things

2023-10-08 18:43 UTC, peppelinux commented on draft-looker-oauth-attested-key-based-client-authentication.md
>  2. A Client Attestation Proof of Possession (PoP) - produced by the client instance.
```suggestion
1. A Client Attestation JWT produced by the client backend.
2. A Client Attestation Proof of Possession (PoP) produced by the client instance.
```

2023-10-23 20:07 UTC, tplooker commented
Closed in favour of changes made in #52

2023-10-23 20:07 UTC, closed without merging